# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6faca233a9a8212b2ebebdcdc87d69cd61c1b41713ca5c941ec2af56bc5f82721710d667c9caad66b196a120f75db1c05fb1ffd148678e553d36618fba3e09aa

test:
  secret_key_base: 06d162200add253ff437ffd5dae602854c8e708b8f09cdca34ccce8f7c41b92acf3605990dadf3f094bec021ad8cb5cc9018afcb64c8672a91b8d7ddf2781761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
